# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roboception/msgs/dynamics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import roboception.msgs.time_pb2
import roboception.msgs.pose_pb2
import roboception.msgs.vector3d_pb2
import roboception.msgs.frame_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='roboception/msgs/dynamics.proto',
  package='roboception.msgs',
  serialized_pb=_b('\n\x1froboception/msgs/dynamics.proto\x12\x10roboception.msgs\x1a\x1broboception/msgs/time.proto\x1a\x1broboception/msgs/pose.proto\x1a\x1froboception/msgs/vector3d.proto\x1a\x1croboception/msgs/frame.proto\"\xd8\x03\n\x08\x44ynamics\x12)\n\ttimestamp\x18\x01 \x01(\x0b\x32\x16.roboception.msgs.Time\x12$\n\x04pose\x18\x02 \x01(\x0b\x32\x16.roboception.msgs.Pose\x12\x12\n\npose_frame\x18\x03 \x01(\t\x12\x33\n\x0flinear_velocity\x18\x04 \x01(\x0b\x32\x1a.roboception.msgs.Vector3d\x12\x1d\n\x15linear_velocity_frame\x18\x05 \x01(\t\x12\x34\n\x10\x61ngular_velocity\x18\x06 \x01(\x0b\x32\x1a.roboception.msgs.Vector3d\x12\x1e\n\x16\x61ngular_velocity_frame\x18\x07 \x01(\t\x12\x37\n\x13linear_acceleration\x18\x08 \x01(\x0b\x32\x1a.roboception.msgs.Vector3d\x12!\n\x19linear_acceleration_frame\x18\t \x01(\t\x12\x16\n\ncovariance\x18\n \x03(\x01\x42\x02\x10\x01\x12\x32\n\x11\x63\x61m2imu_transform\x18\x0b \x01(\x0b\x32\x17.roboception.msgs.Frame\x12\x15\n\rpossible_jump\x18\x0c \x01(\x08\x42&\n\x14\x63om.roboception.msgsB\x0e\x44ynamicsProtos')
  ,
  dependencies=[roboception.msgs.time_pb2.DESCRIPTOR,roboception.msgs.pose_pb2.DESCRIPTOR,roboception.msgs.vector3d_pb2.DESCRIPTOR,roboception.msgs.frame_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DYNAMICS = _descriptor.Descriptor(
  name='Dynamics',
  full_name='roboception.msgs.Dynamics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='roboception.msgs.Dynamics.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='roboception.msgs.Dynamics.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose_frame', full_name='roboception.msgs.Dynamics.pose_frame', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_velocity', full_name='roboception.msgs.Dynamics.linear_velocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_velocity_frame', full_name='roboception.msgs.Dynamics.linear_velocity_frame', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='roboception.msgs.Dynamics.angular_velocity', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular_velocity_frame', full_name='roboception.msgs.Dynamics.angular_velocity_frame', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_acceleration', full_name='roboception.msgs.Dynamics.linear_acceleration', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_acceleration_frame', full_name='roboception.msgs.Dynamics.linear_acceleration_frame', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='roboception.msgs.Dynamics.covariance', index=9,
      number=10, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='cam2imu_transform', full_name='roboception.msgs.Dynamics.cam2imu_transform', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='possible_jump', full_name='roboception.msgs.Dynamics.possible_jump', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=647,
)

_DYNAMICS.fields_by_name['timestamp'].message_type = roboception.msgs.time_pb2._TIME
_DYNAMICS.fields_by_name['pose'].message_type = roboception.msgs.pose_pb2._POSE
_DYNAMICS.fields_by_name['linear_velocity'].message_type = roboception.msgs.vector3d_pb2._VECTOR3D
_DYNAMICS.fields_by_name['angular_velocity'].message_type = roboception.msgs.vector3d_pb2._VECTOR3D
_DYNAMICS.fields_by_name['linear_acceleration'].message_type = roboception.msgs.vector3d_pb2._VECTOR3D
_DYNAMICS.fields_by_name['cam2imu_transform'].message_type = roboception.msgs.frame_pb2._FRAME
DESCRIPTOR.message_types_by_name['Dynamics'] = _DYNAMICS

Dynamics = _reflection.GeneratedProtocolMessageType('Dynamics', (_message.Message,), dict(
  DESCRIPTOR = _DYNAMICS,
  __module__ = 'roboception.msgs.dynamics_pb2'
  # @@protoc_insertion_point(class_scope:roboception.msgs.Dynamics)
  ))
_sym_db.RegisterMessage(Dynamics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024com.roboception.msgsB\016DynamicsProtos'))
_DYNAMICS.fields_by_name['covariance'].has_options = True
_DYNAMICS.fields_by_name['covariance']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
