# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roboception/msgs/frame.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import roboception.msgs.pose_stamped_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='roboception/msgs/frame.proto',
  package='roboception.msgs',
  serialized_pb='\n\x1croboception/msgs/frame.proto\x12\x10roboception.msgs\x1a#roboception/msgs/pose_stamped.proto\"R\n\x05\x46rame\x12+\n\x04pose\x18\x01 \x01(\x0b\x32\x1d.roboception.msgs.PoseStamped\x12\x0e\n\x06parent\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\tB#\n\x14\x63om.roboception.msgsB\x0b\x46rameProtos')




_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='roboception.msgs.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='roboception.msgs.Frame.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='roboception.msgs.Frame.parent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='roboception.msgs.Frame.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=87,
  serialized_end=169,
)

_FRAME.fields_by_name['pose'].message_type = roboception.msgs.pose_stamped_pb2._POSESTAMPED
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME

class Frame(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRAME

  # @@protoc_insertion_point(class_scope:roboception.msgs.Frame)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\024com.roboception.msgsB\013FrameProtos')
# @@protoc_insertion_point(module_scope)
