# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roboception/msgs/imu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import roboception.msgs.time_pb2
import roboception.msgs.vector3d_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='roboception/msgs/imu.proto',
  package='roboception.msgs',
  serialized_pb=_b('\n\x1aroboception/msgs/imu.proto\x12\x10roboception.msgs\x1a\x1broboception/msgs/time.proto\x1a\x1froboception/msgs/vector3d.proto\"\x9f\x01\n\x03Imu\x12)\n\ttimestamp\x18\x01 \x01(\x0b\x32\x16.roboception.msgs.Time\x12\x37\n\x13linear_acceleration\x18\x02 \x01(\x0b\x32\x1a.roboception.msgs.Vector3d\x12\x34\n\x10\x61ngular_velocity\x18\x03 \x01(\x0b\x32\x1a.roboception.msgs.Vector3dB!\n\x14\x63om.roboception.msgsB\tImuProtos')
  ,
  dependencies=[roboception.msgs.time_pb2.DESCRIPTOR,roboception.msgs.vector3d_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMU = _descriptor.Descriptor(
  name='Imu',
  full_name='roboception.msgs.Imu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='roboception.msgs.Imu.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_acceleration', full_name='roboception.msgs.Imu.linear_acceleration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='roboception.msgs.Imu.angular_velocity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=270,
)

_IMU.fields_by_name['timestamp'].message_type = roboception.msgs.time_pb2._TIME
_IMU.fields_by_name['linear_acceleration'].message_type = roboception.msgs.vector3d_pb2._VECTOR3D
_IMU.fields_by_name['angular_velocity'].message_type = roboception.msgs.vector3d_pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Imu'] = _IMU

Imu = _reflection.GeneratedProtocolMessageType('Imu', (_message.Message,), dict(
  DESCRIPTOR = _IMU,
  __module__ = 'roboception.msgs.imu_pb2'
  # @@protoc_insertion_point(class_scope:roboception.msgs.Imu)
  ))
_sym_db.RegisterMessage(Imu)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024com.roboception.msgsB\tImuProtos'))
# @@protoc_insertion_point(module_scope)
