# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roboception/msgs/pose.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import roboception.msgs.vector3d_pb2
import roboception.msgs.quaternion_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='roboception/msgs/pose.proto',
  package='roboception.msgs',
  serialized_pb='\n\x1broboception/msgs/pose.proto\x12\x10roboception.msgs\x1a\x1froboception/msgs/vector3d.proto\x1a!roboception/msgs/quaternion.proto\"\x7f\n\x04Pose\x12,\n\x08position\x18\x01 \x01(\x0b\x32\x1a.roboception.msgs.Vector3d\x12\x31\n\x0borientation\x18\x02 \x01(\x0b\x32\x1c.roboception.msgs.Quaternion\x12\x16\n\ncovariance\x18\x03 \x03(\x01\x42\x02\x10\x01\x42\"\n\x14\x63om.roboception.msgsB\nPoseProtos')




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='roboception.msgs.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='roboception.msgs.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='roboception.msgs.Pose.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='roboception.msgs.Pose.covariance', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=244,
)

_POSE.fields_by_name['position'].message_type = roboception.msgs.vector3d_pb2._VECTOR3D
_POSE.fields_by_name['orientation'].message_type = roboception.msgs.quaternion_pb2._QUATERNION
DESCRIPTOR.message_types_by_name['Pose'] = _POSE

class Pose(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSE

  # @@protoc_insertion_point(class_scope:roboception.msgs.Pose)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\024com.roboception.msgsB\nPoseProtos')
_POSE.fields_by_name['covariance'].has_options = True
_POSE.fields_by_name['covariance']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
