# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roboception/msgs/quaternion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='roboception/msgs/quaternion.proto',
  package='roboception.msgs',
  serialized_pb=_b('\n!roboception/msgs/quaternion.proto\x12\x10roboception.msgs\"8\n\nQuaternion\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\t\n\x01w\x18\x05 \x01(\x01\x42(\n\x14\x63om.roboception.msgsB\x10QuaternionProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUATERNION = _descriptor.Descriptor(
  name='Quaternion',
  full_name='roboception.msgs.Quaternion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='roboception.msgs.Quaternion.x', index=0,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='roboception.msgs.Quaternion.y', index=1,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='roboception.msgs.Quaternion.z', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='roboception.msgs.Quaternion.w', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['Quaternion'] = _QUATERNION

Quaternion = _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNION,
  __module__ = 'roboception.msgs.quaternion_pb2'
  # @@protoc_insertion_point(class_scope:roboception.msgs.Quaternion)
  ))
_sym_db.RegisterMessage(Quaternion)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024com.roboception.msgsB\020QuaternionProtos'))
# @@protoc_insertion_point(module_scope)
