# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roboception/msgs/time.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='roboception/msgs/time.proto',
  package='roboception.msgs',
  serialized_pb='\n\x1broboception/msgs/time.proto\x12\x10roboception.msgs\"!\n\x04Time\x12\x0b\n\x03sec\x18\x01 \x01(\x03\x12\x0c\n\x04nsec\x18\x02 \x01(\x05\x42\"\n\x14\x63om.roboception.msgsB\nTimeProtos')




_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='roboception.msgs.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sec', full_name='roboception.msgs.Time.sec', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nsec', full_name='roboception.msgs.Time.nsec', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['Time'] = _TIME

class Time(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIME

  # @@protoc_insertion_point(class_scope:roboception.msgs.Time)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\024com.roboception.msgsB\nTimeProtos')
# @@protoc_insertion_point(module_scope)
